language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
env:
  global:
    - WP_TRAVISCI=travis:phpunit
    - secure: vBM6kuXkcOOZWKOTdN9RI8pBSIslKeyOh01HPUQ8bchg989w3bvRie9g7FvJ5Yvby3yE1cB0RTECZeTAjpELzuoLjHOe4GB//qoYxEi8WFFJynWx6JHcTE9uML/c9M95KC/B91K4NXQsU7hxTYwWeihCWxNoUVcGqN3EtbmDj3QfjU3zYOMPRKm1vCVAkQiBrMtWtvw9MaVok7P8/DELpj4w0ajejLXIX3Xh+P/rK9NgxxuhM+fnzcir1+813nEevnm0HFPfmiebu4U4tf98UNX9vg/P2g9b0bFMuBVGaE9GhDCz3GmMq1GY3BX3VECOElgvqgnXOVOKcxIqI05XtedOZX1fDeqqJ/g9WQ+/qpAGcIJvlVVvJZCOqyqunvhDCqUM5KkWoJ/fUH/qQbf2AxpcAHbvAmKjlkBZIh2JdQTGDPJS5k5eitYy62sKSE97g1gn49G3KrCbwdCYdp//waGn+vxVwJJ23Fh2VoN55bkW0UPURXPZXIaSfCvZwCo+OxPl5aPof/hMxbjxlMuI6C2f9UD2ltxdiy48EcccEg2ygnRjgcHd5ipDYllMuqtxAX2DTUbl3eDI5YYipSM4ngGFjTZOAWKrae71CKyqCE6WfBipIBP6W0IJHfpBjFwU5eIxjqeIRZP+iuJ6mTAoglzfLoNP64g37MCmloLYahs=
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=0
before_script:
- |
  # Remove Xdebug for a huge performance increase, but not from nightly or hhvm:
    stable='^[0-9\.]+$'
    if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
      phpenv config-rm xdebug.ini
    fi
- |
  # Export Composer's global bin dir to PATH, but not on PHP 5.2:
  if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
    composer config --list --global
    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
  fi
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
    case "$TRAVIS_PHP_VERSION" in
      7.1|7.0|hhvm|nightly)
        echo "Using PHPUnit 5.7"
        composer global require "phpunit/phpunit=5.7.*"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.8"
        composer global require "phpunit/phpunit=4.8.*"
        ;;
      5.2)
        # Do nothing, use default PHPUnit 3.6.x
        echo "Using default PHPUnit, hopefully 3.6"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac
  fi
- mysql --version
- phpenv versions
- php --version
- |
  # Debug PHP extensions, but not on HHVM because the command hangs indefinitely:
  if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
    php -m
  fi
- which phpunit
- phpunit --version
- curl --version
- grunt --version
- git --version
- svn --version
- git clone https://${GFTOKEN}@github.com/gravityforms/gravityforms.git $PWD/tmp/gravityforms
- bash tests/bin/install.sh wordpress_unit_tests root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack:
    secure: d/y3Uz57YmUF+5o2cl7PHqTHq/QFP8qvzI5jurokN9Cb6NKUDuqEZNZn4F6AKQLn+omkGZbOcx2Rbt53jtt2eckRjP+N+yMHUw3vdRZPKouAQf24RXsmcyPb5RbtKZeOrMi8PoyX/pFa6m8aX4SgcKClHgIlS41sOiY/mig/H9/AqzZEFEbBl6hbF48SrbYnwYmLOIbX2ScNKHqsmzR2EIPVZYBsNcQXRz4tEUs1f0d6tIB3BP/kn0+ci2ScX0XzfvkqR1psHeRmB2qt3mUj3S0B/J3VsA8DiakQLdjO0VuLpMdEYCiI7jPoY4rq9MxsILu2rB0w9emNpKrL488wIRyp/g2xmBepmCrFBclfeVJZRrxEGKOWma4cobYOOx5BDGrfBSVPr2S8fgBx3/o59oMauxnriCz8Ul3FtYjvIwd9uDISPCV4lHnD/glQUV+B5AG6usiw/5uuS7oFL5lffwzNzzI4kyfrAsXwdNwSq3T25vQB/rJscgxi97Lrl6J2LU+IOfwwaE74TdJhov1AiXHVBpILSi7Fk7FzcZoE41TYL7emUIF2ODln4A/sgo+j1Poul0jInm5REsUgTCPS89skTObFdCi49N3Ps9YL4WXVTtm2JVJ3oluPsCuiN2FDrdfYflRY3uh5ZEdWgiLmxuOb6ueQsb8vqhThIU2UEms=
